name: drought
channels:
  - conda-forge
  - bioconda
  - base
  - R

dependencies:
  - r-base=4.2.1
  - r-tidyverse=1.3.2
  - python=3.10.6
  - snakemake=7.17.1
  - graphviz=6.0.1
  - radian=0.6.4
  - coreutils=9.1